# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "GitHub"
pre = "github"
url = "https://github.com/Nat-Stephenson"
weight = 10

[[main]]
name = "Resources"
weight = 10

[[main]]
name = "Active Learning"
pageRef = "Posts"
parent = "Resources"
weight = 20

[[main]]
name = "Communities"
parent = "Resources"
pageRef = "Library"
weight = 20

[[main]]
name = "Blogs"
weight = 30

[[main]]
name = "Data Stories"
parent = "Blogs"
pageRef = "Data Stories"
weight = 30

[[main]]
name = "Agile"
parent = "Blogs"
pageRef = "Agile"
weight = 30

[[main]]
name = "Doodles"
parent = "Blogs"
pageRef = "doodles"
weight = 30

[[main]]
name = "Project & Product Management"
parent = "Blogs"
pageRef = "Product Management"
weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = NHS-R Community
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
